### ISSUE TITLE
Soft hyphen not displayed at line break

### ISSUE THREAD

**Issue by tomek1024** [Kozea/WeasyPrint#1214]
After @liZe suggestion in #1023 I'm opening a new issue for a missing hyphen on the end of the line.

After rendering https://zecer.elibri.com.pl/lte/unexpected-justification.html we get (should be "przysz-" at the end of the line)

![image](https://user-images.githubusercontent.com/25573/93350648-283afc00-f839-11ea-8a11-f0622d6ec369.png)

System info:
```
> weasyprint -i
System: Linux
Machine: x86_64
Version: #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
Release: 4.15.0-112-generic

WeasyPrint version: 51
Python version: 3.8.2
Cairo version: 11600
Pango version: 14407
CairoSVG version: 2.4.2
```

**Comment by liZe** [comment]
I don’t know why the soft hyphen is not displayed. As explained in #1023, it looks like a line break before the hyphen during the display. That’s really strange…

**Comment by malnajdi** [comment]
@liZe This is using the latest master branch
![image](https://user-images.githubusercontent.com/15247545/95676524-5658f500-0bc7-11eb-8144-b1bd0ec4bd5f.png)

**Comment by exploids** [comment]
Is there any update on this? 😄

**Comment by liZe** [comment]
> Is there any update on this? smile

Unfortunately no 😒.

**Comment by exploids** [comment]
Interestingly when using the `lang="xy"` attribute and the `hyphens: auto` CSS property, the automatically inserted hyphens are rendered correctly.

Automatic hyphens:

```html
<!DOCTYPE html>
<html lang="en">
	<p style="width: 3cm; background: yellow; hyphens: auto">
		Hippopotomonstrosesquippedaliophobia
	</p>
</html>
```

![image](https://user-images.githubusercontent.com/32574654/148686879-a634cc55-672e-44ab-b710-c089145de0db.png)

After inserting a soft hyphen:

```html
<!DOCTYPE html>
<html lang="en">
	<p style="width: 3cm; background: yellow; hyphens: auto">
		Hippopo&shy;tomonstrosesquippedaliophobia
	</p>
</html>
```

![image](https://user-images.githubusercontent.com/32574654/148686954-2dd0c494-1217-4d87-b79d-954851b55257.png)

**Comment by liZe** [comment]
I get the hyphen with your second example, that’s strange. Could you please give us more information about your system, including your version of Pango?

**Comment by grewn0uille** [comment]
Hello!
This issue has been fixed by https://github.com/Kozea/WeasyPrint/commit/424f080311424356d88db34cc33891aa87f12cca.

**Comment by anghenfil** [comment]
I'm still experiencing this issue when adding soft hyphens and using hyphens: auto.

**Comment by liZe** [comment]
Hi @anghenfil,
Can you please share your HTML/CSS files?
