### ISSUE TITLE
Fail to render position absolute display flex element due to non-iterable PageBox

### ISSUE THREAD

**Issue by n1ngu** [Kozea/WeasyPrint#1536]
The recent update of weasyprint 54 raises an exception when rendering many of my templates due to the usage of absolute flex elements.

I think this html
```
<!doctype html>
<html>
  <head>
    <style>
p {
    position: fixed;
    display: flex;
}
    </style>
    <title>Test</title>
  </head>
  <body>
    <p>Hello</p>
  </body>
</html>
```
is enough to reproduce the issue.

AFAIU the culprit might this changes https://github.com/Kozea/WeasyPrint/commit/f5d6d54ccacaa700d254861b5f83abde98a05be8#diff-3c982105b0ba6decc90731974c5bf2d4f37f0656b1ab8267bedecdf2e3d054d5 in the layout/absolute.py file, where the parameters `containing_block`and `containing_block_sizes` were swapped in the `absolute_flex` function definition but not its call from `absolute_box_layout` function (this is where the traces are coming from)
```
[...]
  File "/app/.venv/lib/python3.9/site-packages/weasyprint/layout/page.py", line 596, in make_page
    absolute_layout(
  File "/app/.venv/lib/python3.9/site-packages/weasyprint/layout/absolute.py", line 272, in absolute_layout
    new_box, resume_at = absolute_box_layout(
  File "/app/.venv/lib/python3.9/site-packages/weasyprint/layout/absolute.py", line 307, in absolute_box_layout
    new_box, resume_at = absolute_flex(
  File "/app/.venv/lib/python3.9/site-packages/weasyprint/layout/absolute.py", line 234, in absolute_flex
    cb_x, cb_y, cb_width, cb_height = containing_block_sizes
TypeError: cannot unpack non-iterable PageBox object
```

**Comment by n1ngu** [comment]
Due to the amount of refactoring that went on that file, I am somewhat astray on how this should be addressed. I'd need a fair amount of guidance to contribute any kind of patch. I hope the posted html snippet aids to increase the test suite nonetheless.

**Comment by liZe** [comment]
Hello!

Thanks for the bug report, and thanks a lot for the snippet! The bug was caused by the refactoring, and by these stupid `original_cb`/`cb` parameters (there’s already a TODO in the code about that). It should be fixed now.

**Comment by mgazzin** [comment]
I have just installed today and it still have the bug. When are you going to update .whl @liZe @grewn0uille ?

**Comment by grewn0uille** [comment]
Soon :)

**Comment by varac** [comment]
Using the [example cli cmd from the docs](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#command-line):

```
❯ weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf
...
   new_box, resume_at = absolute_box_layout(
  File "/home/varac/projects/pdf/WeasyPrint/.direnv/python-3.9.7/lib/python3.9/site-packages/weasyprint/layout/absolute.py", line 307, in absolute_box_layout
    new_box, resume_at = absolute_flex(
  File "/home/varac/projects/pdf/WeasyPrint/.direnv/python-3.9.7/lib/python3.9/site-packages/weasyprint/layout/absolute.py", line 234, in absolute_flex
    cb_x, cb_y, cb_width, cb_height = containing_block_sizes
TypeError: cannot unpack non-iterable BlockBox object

❯ weasyprint --version
WeasyPrint version 54.0
```
